title: <p align="center"> Debarpan Das </p>

logo: "/images/picture.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/debarpan-das-msc-917563137/">LinkedIn</a> |
  <a href="https://github.com/Debarpan98">GitHub</a> |
  <a href="https://scholar.google.ca/citations?user=6oSwVPoAAAAJ&hl=en">Google Scholar</a>
  </p>
  
  <p align="justify">
  AI enthusiast dedicated to unlocking the potential of AI in healthcare. My current research interests include computer vision and deep learning.
  <br><br>
  As a Clinical Research Specialist at Kent Imaging, I analyze large volumes of multimodal clinical image databases and Near Infrared Spectroscopy (NIRS) signals. I apply my skills and knowledge in advanced analytics, computer vision, AI-Engineering and statistical modeling to build both predictive as well as inferential models helping shape clinical & business strategy as well as elevating patient outcomes.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
