title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/debarpan-das-msc-917563137//">LinkedIn</a> |
  <a href="https://github.com/Debarpan98">GitHub</a>
  </p>
  
  <p align="justify">
  AI enthusiast dedicated to unlocking the potential of AI for businesses, revolutionizing industries one algorithm at a time.  
  <br><br>
  As a Clinical Research and Data Specialist at Kent Imaging, I develop and deploy machine learning models and advanced statistical algorithms to process and understand large volumes of multimodal clinical data and Near Infrared Spectroscopy (NIRS) signals. I apply my skills and knowledge in advanced analytics, computer vision, AI-Engineering and statistical modeling to create innovative solutions and strategic tools for the healthcare industry.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
